### ISSUE TITLE
做一个 UserInfo 对象

### ISSUE THREAD

**Issue by sunng87** [lzwjava/rocket-chat#2]
在 UserHelper 里不需要两个接口分别返回 display name 或者 avatar，直接返回一个 UserInfo 对象就可以了。内部用 UsereHelper 的时候可能还要支持缓存之类的逻辑，不能每次去网络取。

**Comment by huyansheng3** [comment]
大哥，不行，到不了AS啊！

**Comment by lzwjava** [comment]
fixed in https://github.com/leancloud/leanchat-android
